### ISSUE TITLE
🚫 Implement "Lock New Issues" Workflow to Reduce Notifications and Support Maintainers

### ISSUE THREAD

**Issue by Nishitbaria** [SurajPratap10/Imagine_AI#538]
### Description

**As a repository maintainer, I propose the implementation of a workflow that aims to minimize notifications and enhance the support provided to maintainers. This workflow will automatically lock newly opened issues and provide guidance to contributors.**

### Screenshots

```
name: 'Lock new issues'

on:
  issues:
    types: opened

permissions:
  issues: write

jobs:
  action:
    runs-on: ubuntu-latest
    steps:
      - name: Lock issues
        uses: dessant/repo-lockdown@v3
        with:
          close-issue: false
          exclude-issue-labels: 'gssoc23.'
          process-only: 'issues'
          skip-closed-issue-comment: true
          issue-comment: >
            To reduce notifications, issues are locked. Your issue will be unlocked when we add the label `gssoc23`. If you're participating in GSSoC'23, please add the `gssoc23` label to your issue.

```

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines]
- [X] I have read the discussion tab thoroughly and got the project idea 
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor
