### ISSUE TITLE
 refactor: lock workflow for improved functionality 🔒✨ 

### ISSUE THREAD

**Issue by 0xabdulkhalid** [SurajPratap10/Imagine_AI#719]
## Description

- There are currently issues with the `lock.yml` workflow in the this repository. 
- A typographical error in the exclusion label (`gssoc23.` instead of `gssoc23`) is causing the workflow to misbehave. 
- Additionally, the **current workflow does not add the "locked" label to newly created issues, nor does it unlock the conversation after the issue gets assigned**.
- To correct this and improve our repository management, I propose we update the workflow with the corrected script below:

```
name: "issue lockdown"

on:
  issues:
    types: opened

permissions:
  issues: write

jobs:
  action:
    runs-on: ubuntu-latest
    steps:
      - uses: dessant/repo-lockdown@v3
        with:
          close-issue: false
          process-only: "issues"
          issue-labels: "🔒 locked"
          exclude-issue-labels: "gssoc23"
          skip-closed-issue-comment: true
          issue-comment: >
            To reduce notifications, issues are locked. Your issue will be unlocked when we add the label, `gssoc23`.
```
- This updated script should fix the mentioned issues, ensuring newly opened issues are properly locked and labeled, excluding those labeled with "gssoc23". It will also ensure that the conversations are unlocked after issue assignment.

- This change will greatly improve our issue tracking system, streamline collaboration, and enhance overall project management. I kindly ask for your attention to this matter.
