### ISSUE TITLE
feat : Lint Commit Messages Workflow using Commitlint GitHub Action ✨

### ISSUE THREAD

**Issue by Nishitbaria** [SurajPratap10/Imagine_AI#770]
Description

 I propose adding a new workflow called "Lint Commit Messages." This workflow will be triggered on pull requests and pushes to help maintain proper commit message formatting and adherence to the Conventional Commits guideline. To achieve this, we will utilize the "Commitlint GitHub Action" provided by the "wagoid/commitlint-github-action" repository.

**Proposed Workflow:**

```yaml
name: Lint Commit Messages
on: [pull_request, push]

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Lint Commit Messages
        uses: wagoid/commitlint-github-action@v4
```

**What it does**

The "Lint Commit Messages" workflow employs the "Commitlint GitHub Action" to automatically check the commit messages in each pull request and push event. The action parses commit messages against the Conventional Commits specification and verifies whether they follow the required format. If a commit message does not adhere to the defined rules, the action will raise a warning or failure, depending on the severity of the violation.

By introducing this workflow, we aim to encourage contributors to write meaningful, well-structured commit messages, promoting collaboration and easing the review process.

**When it occurs:**

The "Lint Commit Messages" workflow is triggered on the following events:
1. **pull_request**: Whenever a new pull request is opened or an existing one is updated.
2. **push**: Whenever code is pushed to any branch in the repository.
